import { DataTypes, literal, type QueryInterface } from 'sequelize';

/**
 * Transactional outbox for domain events consumed by the analytics pipeline.
 *
 * WHY AN OUTBOX AND NOT A DIRECT KAFKA PUBLISH.
 *
 * The events describe money movement — credits granted, campaigns funded. A
 * publish made after COMMIT can be lost (process dies between the two), and a
 * publish made before COMMIT can describe a transaction that then rolls back.
 * Either way the warehouse disagrees with the ledger, silently.
 *
 * Writing the event row in the SAME transaction as the ledger row makes the two
 * atomic: an event exists if and only if the change it describes committed. A
 * separate relay process (src/outbox/relay.ts) then publishes unpublished rows
 * to Kafka. Delivery is at-least-once; consumers dedupe on `event_id`.
 *
 * It also keeps Kafka out of the request path entirely: a broker outage delays
 * analytics, it never fails a checkout or a funding request.
 */
export async function up(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.createTable('outbox_events', {
    id: {
      type: DataTypes.BIGINT.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    // UUID generated by the producer. The idempotency key downstream.
    event_id: {
      type: DataTypes.CHAR(36),
      allowNull: false,
    },
    topic: {
      type: DataTypes.STRING(255),
      allowNull: false,
    },
    event_type: {
      type: DataTypes.STRING(100),
      allowNull: false,
    },
    aggregate_type: {
      type: DataTypes.STRING(50),
      allowNull: false,
    },
    // Used as the Kafka message key, so all events for one aggregate land on
    // one partition and are consumed in order.
    aggregate_id: {
      type: DataTypes.STRING(64),
      allowNull: false,
    },
    payload: {
      type: DataTypes.JSON,
      allowNull: false,
    },
    occurred_at: {
      type: DataTypes.DATE(3),
      allowNull: false,
    },
    published_at: {
      type: DataTypes.DATE(3),
      allowNull: true,
    },
    attempts: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      defaultValue: 0,
    },
    last_error: {
      type: DataTypes.STRING(1024),
      allowNull: true,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: literal('CURRENT_TIMESTAMP'),
    },
  });

  await queryInterface.addConstraint('outbox_events', {
    fields: ['event_id'],
    type: 'unique',
    name: 'uq_outbox_events_event_id',
  });

  // The relay's scan: WHERE published_at IS NULL ORDER BY id.
  await queryInterface.addIndex('outbox_events', ['published_at', 'id'], {
    name: 'ix_outbox_events_unpublished',
  });
}

export async function down(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.dropTable('outbox_events');
}
