-- ============================================================================
-- 01 — Role-based access control.
--
-- Two layers of roles, the standard Snowflake pattern:
--
--   ACCESS ROLES (*_AR)      hold privileges on objects. Never granted to users.
--   FUNCTIONAL ROLES         are granted to users and inherit access roles.
--
-- Entitlements that masking / row access policies test for are themselves
-- access roles (PII_READER_AR, FINANCIAL_READER_AR, ALL_MODULES_AR). Policies
-- ask IS_ROLE_IN_SESSION('<entitlement>'), so who-can-see-what is changed with
-- a GRANT, audited like any grant, and never by editing a policy body.
--
-- Platform role -> functional role (mirrors analytics_service/rbac.py):
--   member  -> ANALYTICS_MEMBER     own data only (enforced by the API)
--   analyst -> ANALYTICS_ANALYST    aggregates; PII + money masked; module-scoped
--   finance -> ANALYTICS_FINANCE    + money
--   admin   -> ANALYTICS_ADMIN      + PII, RAW, governance views
--
-- Separation of duties: ANALYTICS_GOVERNOR owns policies and tags but is NOT
-- granted data-read entitlements; data roles cannot alter the policies that
-- constrain them.
-- ============================================================================

USE ROLE USERADMIN;

-- Access roles.
CREATE ROLE IF NOT EXISTS RAW_WRITE_AR        COMMENT = 'Insert/merge into RAW.';
CREATE ROLE IF NOT EXISTS RAW_READ_AR         COMMENT = 'Read RAW event payloads (contain PII).';
CREATE ROLE IF NOT EXISTS CORE_READ_AR        COMMENT = 'Read governed CORE views.';
CREATE ROLE IF NOT EXISTS GOVERNANCE_READ_AR  COMMENT = 'Read audit log and policy catalogue.';

-- Entitlements tested by policies.
CREATE ROLE IF NOT EXISTS PII_READER_AR       COMMENT = 'Entitlement: unmasked personal data.';
CREATE ROLE IF NOT EXISTS FINANCIAL_READER_AR COMMENT = 'Entitlement: unmasked money amounts.';
CREATE ROLE IF NOT EXISTS ALL_MODULES_AR      COMMENT = 'Entitlement: rows from every module.';

-- Functional roles.
CREATE ROLE IF NOT EXISTS ANALYTICS_LOADER   COMMENT = 'Service: Kafka consumer.';
CREATE ROLE IF NOT EXISTS ANALYTICS_MEMBER   COMMENT = 'Platform role: member.';
CREATE ROLE IF NOT EXISTS ANALYTICS_ANALYST  COMMENT = 'Platform role: analyst.';
CREATE ROLE IF NOT EXISTS ANALYTICS_FINANCE  COMMENT = 'Platform role: finance.';
CREATE ROLE IF NOT EXISTS ANALYTICS_ADMIN    COMMENT = 'Platform role: admin.';
CREATE ROLE IF NOT EXISTS ANALYTICS_GOVERNOR COMMENT = 'Owns tags and policies. No data entitlements.';

USE ROLE SECURITYADMIN;

-- Functional role composition.
GRANT ROLE RAW_WRITE_AR        TO ROLE ANALYTICS_LOADER;

GRANT ROLE CORE_READ_AR        TO ROLE ANALYTICS_MEMBER;
GRANT ROLE ALL_MODULES_AR      TO ROLE ANALYTICS_MEMBER;   -- row scope is per-user, applied by the API

GRANT ROLE CORE_READ_AR        TO ROLE ANALYTICS_ANALYST;  -- modules via GOVERNANCE.ROLE_MODULE_ACCESS

GRANT ROLE CORE_READ_AR        TO ROLE ANALYTICS_FINANCE;
GRANT ROLE FINANCIAL_READER_AR TO ROLE ANALYTICS_FINANCE;
GRANT ROLE ALL_MODULES_AR      TO ROLE ANALYTICS_FINANCE;

GRANT ROLE CORE_READ_AR        TO ROLE ANALYTICS_ADMIN;
GRANT ROLE RAW_READ_AR         TO ROLE ANALYTICS_ADMIN;
GRANT ROLE GOVERNANCE_READ_AR  TO ROLE ANALYTICS_ADMIN;
GRANT ROLE PII_READER_AR       TO ROLE ANALYTICS_ADMIN;
GRANT ROLE FINANCIAL_READER_AR TO ROLE ANALYTICS_ADMIN;
GRANT ROLE ALL_MODULES_AR      TO ROLE ANALYTICS_ADMIN;

GRANT ROLE GOVERNANCE_READ_AR  TO ROLE ANALYTICS_GOVERNOR;

-- Every custom role rolls up to SYSADMIN so ownership stays manageable.
GRANT ROLE ANALYTICS_LOADER   TO ROLE SYSADMIN;
GRANT ROLE ANALYTICS_MEMBER   TO ROLE SYSADMIN;
GRANT ROLE ANALYTICS_ANALYST  TO ROLE SYSADMIN;
GRANT ROLE ANALYTICS_FINANCE  TO ROLE SYSADMIN;
GRANT ROLE ANALYTICS_ADMIN    TO ROLE SYSADMIN;
GRANT ROLE ANALYTICS_GOVERNOR TO ROLE SYSADMIN;

-- Warehouses.
GRANT USAGE ON WAREHOUSE INGEST_WH    TO ROLE ANALYTICS_LOADER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_MEMBER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_FINANCE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_ADMIN;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE ANALYTICS_GOVERNOR;

-- Database and schema usage.
GRANT USAGE ON DATABASE INFLUENCER_ANALYTICS TO ROLE RAW_WRITE_AR;
GRANT USAGE ON DATABASE INFLUENCER_ANALYTICS TO ROLE RAW_READ_AR;
GRANT USAGE ON DATABASE INFLUENCER_ANALYTICS TO ROLE CORE_READ_AR;
GRANT USAGE ON DATABASE INFLUENCER_ANALYTICS TO ROLE GOVERNANCE_READ_AR;
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.RAW        TO ROLE RAW_WRITE_AR;
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.RAW        TO ROLE RAW_READ_AR;
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.CORE       TO ROLE CORE_READ_AR;
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.GOVERNANCE TO ROLE GOVERNANCE_READ_AR;

-- Object privileges, including FUTURE grants so new views need no extra step.
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA INFLUENCER_ANALYTICS.RAW TO ROLE RAW_WRITE_AR;
GRANT SELECT         ON FUTURE TABLES IN SCHEMA INFLUENCER_ANALYTICS.RAW TO ROLE RAW_READ_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INFLUENCER_ANALYTICS.CORE       TO ROLE CORE_READ_AR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INFLUENCER_ANALYTICS.GOVERNANCE TO ROLE GOVERNANCE_READ_AR;
-- The loader writes the API access log.
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.GOVERNANCE TO ROLE RAW_WRITE_AR;

-- Governor: create and apply tags and policies; nothing else.
GRANT USAGE ON DATABASE INFLUENCER_ANALYTICS TO ROLE ANALYTICS_GOVERNOR;
GRANT USAGE ON SCHEMA INFLUENCER_ANALYTICS.CORE TO ROLE ANALYTICS_GOVERNOR;
GRANT CREATE TAG, CREATE MASKING POLICY, CREATE ROW ACCESS POLICY, CREATE TABLE, CREATE VIEW,
      CREATE PROCEDURE, CREATE TASK
  ON SCHEMA INFLUENCER_ANALYTICS.GOVERNANCE TO ROLE ANALYTICS_GOVERNOR;

USE ROLE ACCOUNTADMIN;
GRANT APPLY MASKING POLICY    ON ACCOUNT TO ROLE ANALYTICS_GOVERNOR;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE ANALYTICS_GOVERNOR;
GRANT APPLY TAG               ON ACCOUNT TO ROLE ANALYTICS_GOVERNOR;
GRANT EXECUTE TASK            ON ACCOUNT TO ROLE ANALYTICS_GOVERNOR;
-- ACCESS_HISTORY / POLICY_REFERENCES for the governance views.
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ANALYTICS_GOVERNOR;

-- ── Service users ───────────────────────────────────────────────────────────
-- Key-pair auth only (TYPE = SERVICE disallows passwords and MFA prompts).
-- Set RSA_PUBLIC_KEY after generating the pair; see analytics/README.md.
--
-- DEFAULT_SECONDARY_ROLES = () IS LOAD-BEARING for the API user. It holds every
-- functional reader role so it can switch per request; with secondary roles
-- enabled, IS_ROLE_IN_SESSION would see ALL of them in every session and the
-- masking policies would unmask everything for everyone.
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS ANALYTICS_LOADER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = ANALYTICS_LOADER
  DEFAULT_WAREHOUSE = INGEST_WH
  DEFAULT_SECONDARY_ROLES = ()
  COMMENT = 'analytics consumer (Kafka -> RAW)';

CREATE USER IF NOT EXISTS ANALYTICS_API_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = ANALYTICS_MEMBER
  DEFAULT_WAREHOUSE = ANALYTICS_WH
  DEFAULT_SECONDARY_ROLES = ()
  COMMENT = 'analytics API; switches to the caller''s mapped role per query';

USE ROLE SECURITYADMIN;
GRANT ROLE ANALYTICS_LOADER  TO USER ANALYTICS_LOADER_SVC;
GRANT ROLE ANALYTICS_MEMBER  TO USER ANALYTICS_API_SVC;
GRANT ROLE ANALYTICS_ANALYST TO USER ANALYTICS_API_SVC;
GRANT ROLE ANALYTICS_FINANCE TO USER ANALYTICS_API_SVC;
GRANT ROLE ANALYTICS_ADMIN   TO USER ANALYTICS_API_SVC;

-- Network policy: service users may only connect from your egress IPs.
-- CREATE NETWORK POLICY ANALYTICS_SVC_NETWORK ALLOWED_IP_LIST = ('203.0.113.0/24');
-- ALTER USER ANALYTICS_LOADER_SVC SET NETWORK_POLICY = ANALYTICS_SVC_NETWORK;
-- ALTER USER ANALYTICS_API_SVC    SET NETWORK_POLICY = ANALYTICS_SVC_NETWORK;
